### ISSUE TITLE
Feedback from Team

### ISSUE THREAD

**Issue by hillkai** [cozmosu/Resources#3]
Come up with questions/create forms for feedback for post team outreach in a google form

**Comment by Aidenjn** [comment]
Check out this form:
[https://forms.gle/CEqPzyVyCqqnxeaF9](https://forms.gle/CEqPzyVyCqqnxeaF9)

**Comment by hillkai** [comment]
I think we need to make the form shorter. I also think we need to get rid of the short answer questions. I like how the form is fun, but we may need to make it more professional because we will probably want to use our feedback for the research paper, which will need to have professional language.

**Comment by Aidenjn** [comment]
Lets go over this together today
